import type { FeedAction, FeedItem, FeedPage, FeedProfile } from "./types";
type UnknownRecord = Record<string, unknown>;
const record = (value:unknown):UnknownRecord => value && typeof value === "object" ? value as UnknownRecord : {};
const string = (value:unknown):string|null => typeof value === "string" && value.trim() ? value : null;
const number = (value:unknown):number|undefined => typeof value === "number" && Number.isFinite(value) ? value : undefined;
function strings(value:unknown):string[] { if(Array.isArray(value)) return value.map((entry)=>typeof entry === "string" ? entry : string(record(entry).text) ?? string(record(entry).label)).filter((entry):entry is string=>Boolean(entry)); if(typeof value === "string") { try{return strings(JSON.parse(value));}catch{return value.split("\n").map((entry)=>entry.trim()).filter(Boolean);} } return []; }
function isToday(value:string|null) { if(!value)return false; const date=new Date(value),now=new Date(); return !Number.isNaN(date.getTime())&&date.getFullYear()===now.getFullYear()&&date.getMonth()===now.getMonth()&&date.getDate()===now.getDate(); }
function normalizeItem(value:unknown):FeedItem {
  const row=record(value),post=record(row.post),source=record(post.source??row.source),metrics=record(post.metrics??row.metrics);
  const postedAt=string(post.postedAt??post.posted_at??row.postedAt??row.posted_at??post.scraped_at);
  const postId=String(post.id??row.postId??row.post_id??row.id??crypto.randomUUID());
  return { id:String(row.id??`${postId}:${row.profileId??row.profile_id??"feed"}`), postId, author:string(source.name??post.author??row.author??row.source_name??source.handle??post.handle??row.source_handle)??"unknown", handle:string(source.handle??post.handle??row.handle??row.source_handle), text:string(post.text??row.text??post.caption??row.caption)??"", url:string(post.url??row.url??row.sourceUrl??row.source_url), postedAt, mediaUrl:string(post.mediaUrl??post.media_url??post.thumb_path??row.mediaUrl??row.media_url??row.thumb_path), bestAngle:string(row.bestAngle??row.best_angle??row.angle), lenses:strings(row.lenses??row.stableLenses??row.stable_lenses), wildcard:string(row.wildcard??row.wildcardFrame??row.wildcard_frame), isFreshToday:typeof row.isFreshToday==="boolean"?row.isFreshToday:typeof row.freshToday==="boolean"?row.freshToday:typeof row.is_fresh_today==="boolean"?row.is_fresh_today:isToday(postedAt), metrics:{ likes:number(metrics.likes??metrics.like_count??post.likes??post.like_count??row.likes??row.like_count), replies:number(metrics.replies??metrics.reply_count??post.replies??post.reply_count??row.replies??row.reply_count), reposts:number(metrics.reposts??metrics.retweet_count??post.reposts??post.retweet_count??row.reposts??row.retweet_count), views:number(metrics.views??metrics.view_count??post.views??post.view_count??row.views??row.view_count??row.impressions) } };
}
export async function getFeed(profile:FeedProfile,cursor:string|null,signal?:AbortSignal):Promise<FeedPage> { const params=new URLSearchParams({profile,limit:"20"}); if(cursor)params.set("cursor",cursor); const response=await fetch(`/api/feed?${params}`,{cache:"no-store",signal}); if(!response.ok)throw new Error(`feed request failed (${response.status})`); const data=record(await response.json()); const raw=Array.isArray(data.items)?data.items:Array.isArray(data.data)?data.data:Array.isArray(data.posts)?data.posts:[]; return {items:raw.map(normalizeItem),nextCursor:string(data.nextCursor??data.next_cursor??data.cursor),sessionId:string(data.sessionId??data.session_id)}; }
export async function sendInteraction(input:{profileId:FeedProfile;targetId:string;action:FeedAction;sessionId:string|null;comment?:string;metadata?:Record<string,string>}):Promise<string|null> { const response=await fetch("/api/feed/interactions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({profile:input.profileId,postId:Number(input.targetId),action:input.action,sessionId:input.sessionId??undefined,comment:input.comment,metadata:input.metadata,targetType:"post",targetId:input.targetId})}); if(!response.ok)throw new Error(`interaction failed (${response.status})`); const data=record(await response.json()); return string(data.suggestedNextMove??data.suggested_next_move??data.suggestion); }
