export const CREATOR_SCRIPTS = {
  "DZFnttWijxS": "Databricks is the hardest company I've tried to explain yet. This is part seven in my series explaining top private tech companies. For decades, companies stored their data in one of two places. A data warehouse, which is perfect for structured data like spreadsheets and order forms. It's fast and reliable, but expensive and rigid. Or a data lake, but for messier data like videos and images. It's cheap and flexible, but slow and unreliable. Most large companies use both. Two separate systems, two teams managing the whole mess. In 2013, seven researchers from Berkeley built a way to process massive data sets by distributing the work across thousands of computers at the same time. They called it Apache Spark. On top of Spark, they built something called the Lakehouse. A hybrid of the two, they combined the best of both. Fast, reliable, cheap and flexible. Only possible because it was built on Spark. Then they made a strange decision. They open sourced both Apache Spark and the Lakehouse, giving it away entirely for free. It bet that if the world built on top of their technology, the adoption would create a moat. It totally worked. Over the next decade, millions of developers across thousands of big companies built their entire data infrastructure on Spark. Databricks instead sold proprietary features and managed platform service on top of this open source foundation. In 2022, when chat GPT was released, Databricks was pretty perfectly positioned. Their customers could now build AI directly on top of the data they already had using Databricks for retrieval, model training and autonomous agents, and then pay Databricks like a utility bill. The more AI workloads they ran, the higher the utility bill. Databricks existing infrastructure just became infinitely more valuable because of AI. The revenue growth is wild. From 200 million in 2020 to a $5.4 billion run rate in 2026, roughly 27X in six years, with the curve deepening every year after chat GPT. Over that period, Databricks raised 20 billion from Andreessen Horowitz, Thrive, NVIDIA, and others with a current valuation of 134 billion and IPO is on the horizon. If data really is the new oil, Databricks owned the pipeline and they built it by letting the oil flow freely.",
  "Dcd0nZkCnAa": "Energy is getting really scarce for AI, but there's one company that turned that problem into a super surprising advantage. Crusoe is just eight years old, and it's now one of the most valuable private tech companies. Here's the crux of the energy problem. Our demand for AI is running way ahead of what our entire energy grid can deliver. The densest cluster of AI data centers on earth is in Northern Virginia, about four gigawatts. And AWS, Azure, and everyone else in the hyperscaler category is plugging in there, but it's already full. If you wanted to add another 100 megawatts, the average wait time is seven whole years. Crusoe proposed a better way, moving you off the grid waitlist entirely by finding hidden energy sources that nobody else can use. The company was started in 2018 by two friends, Chase from Quanttrading and Cully from the energy sector. Their first product used trapped energy from oil fields, where methane gas was being burned off into the air. They rigged up shipping container size boxes with generators and computers to sit nearby, capture that methane gas, and use it to power Bitcoin mining. Pretty solid business. Turns out AI training also has similar power needs. So in 2024, Oracle put out an RFP for 100 megawatts of power for an unnamed customer. This turned out to be open AI. People lined up to bid and claimed they could cut seven years down to two. Chase said he was the 35th person to get that call, nowhere near the top, but he said he could get them that power in just one year by building it in Abilene, Texas, using a similar idea. West Texas's wind country and decades of tax credits built up a lot of wind turbines out there, but that same grid clog meant that about a fifth of Texas renewable power never made it into supply. It's trapped. So rather than move the power to the demand, Crusoe moved the demand to the power. They won the bid and built a huge campus. It's 90 acres, 4 million square feet, and they've had to add about a gigawatt of power from gas turbines, too, just to meet the speed requirements needed. When complete, it'll drop about a third as much energy as the whole Northern Virginia region in just one campus. Crusoe raised last at a $10 billion valuation in October, and reportedly, they're in talks to raise at $30 billion right now, with rumors of an IPO on the horizon. We'll see if this trapped energy play can take them all the way.",
  "DcQ5PNeC6-s": "Did you see that mid-journey about CoStar, the astrology app, and SpaceX about CURSOR? It's a rocket company buying a coding tool. These don't maybe seem related to you, but they fit a pattern, and I want to give it a name. I'm going to make a prediction here. I think we're entering the era of the American Zaibatsu. If you're not familiar with the Zaibatsu, I learned this term in Japan. It's effectively a large family-controlled industrial and financial conglomerate. So these were huge in Japan from the beginning of the Meiji Restoration through World War II. They became really large and powerful because they could have a central holding company, an in-house bank, and diverse individual subsidiaries all feeding off of and supporting each other. They did mining, shipping, banking, foreign trade, and manufacturing, and then they were dissolved in World War II from the Allied forces for being too powerful. For better or worse, I think AI labs have a lot of the same qualities for a few reasons. So take SpaceX as an example. You've got SpaceX, parent company, they make rockets, but within that you have Starlink, which is a huge portion of the revenue necessary for the rocket business. In addition, you have XAI, which includes Twitter, formerly Twitter, which is now X, Cursor, and Supercomputer, and Grok, and everything that that controls that's on that entity. And then you also have all these other Elon companies, Neuralink, Boring Company, Tesla, obviously. The ethos of these companies is going to be related more and more over the next decade, I'm sure of it. And then you go to a company like Mid-Journey, opposite side of the scale in terms of capital and similar in a lot of ways. So they're exhibiting similar behaviors, right? They've got recently announced a CT scanner, an entire health device. That's really beautiful, by the way, I'm super impressed by it. And they have this core business that's an image generation business, like what are those two things doing together? And then a few weeks after the scanner, they announced they're acquiring CoStar, an astrology app. On the surface, none of these have anything to do with each other. I can see how image generation needs a distribution channel that CoStar offers, but it just keeps me head scratching about what companies are going to be in this era where we see a rebundling.",
  "Dcd1OqeCXsL": "If you want your captions to look this cinematic, I've turned this editing style into a skill that you can give it to your AI because these type of marketing videos have really been popping off. To set it up, you first need to install the Hyperframes project locally. I have a YouTube video that walks you through step by step. Then download this skill onto your desktop, give AI access to the project folder, drop in your footage, then ask it to apply cinematic caption style. Instead of basic subtitles, it creates these motion captions that makes important words bigger, translucent, animated, and timed to what's being said. If you want to try it out, comment skill and I'll send it to you.",
  "DcYhrFHiVw8": "Here's how I use AI to add motion graphics to my video. Let's do a live editing session together. I already have this video fully trimmed. I just need text animations edit to export a video. So inside of my AI operating system, I have my hyper frame project folder. And then underneath here, I create a new folder called AI intake. I'm just gonna drop this video right in here. Then I'm going to open up the chat GPT desktop app. I like to use chat GPT because it's more token efficient. You can use whatever AI you want. And instead of a new chat, you're going to select that folder where we have the video. Okay, now I'm just going to talk to it. I want you to edit the raw video. I dropped inside a folder called AI OS intake. The style should feel clean, translucent, modern editorial. For the color, I want you to use lime green similar to the shirt the character is wearing and use the bright turquoise blue matching the speaker nail color. For the first clip add an animated text overlay on screen that says steal my nine AI setup questions. So as I introduce each question, I want a visual pop-up that has a clear number count. And then also a short phrase based on this list I provided for you. Show me what you got. So this is all the prompt I just spoke. And I have the specific texts I wanted to add. Make sure your planning mode is turned on. I'm just going to fire this. Okay, now it's given me the plan. It picked up the color, all the texts I wanted to add. I'm just going to quickly review this and see if I catch anything. It looks good. The only thing I would say is you don't need to add a dash between the number Q zero and the text you can implement. Worked for 16 minutes. And we now have the video ready. So let's take a look. Here at night, warning questions to turn your AI into intelligent copilot is built around your work and life.",
  "DcWQxOriYU8": "Here are 9 onboarding questions to turn your AI into intelligent copilot that's built around your work and life. First, is this operating system built for your business job or personal life that shapes all the context that comes next. Start with what's taking up too much of your time. What would you delegate or automate first? If you could, and give AI basic picture of your world, what you do, who you do it for, what you ultimately trying to accomplish and walk it through how things get done. Think your invoicing workflow, your scheduling workflow or how you onboarding a new person. And this is every tools you use lists what each one is for, what is connected to. This explains where work comes in, where it goes out, things, emails, DMs, forms, calls, calendars. And this explains who's involved in your work. Do you have a team contractor? Are you looking to hire anyone? This explains your logo, file, color, fonts, template, design file, save them into a folder and give AI access. Finally, you want to paste in two to three writing samples for it to learn your tone of voice. I want my exact intake form so you can install it and have AI walk through the entire setup process. Just comment intake and I'll send it to you.",
  "DcLtNI2i8yU": "This is The Weirdest Company Winning in AI, Part 3.\nThis story's got lasers, mirrors, Nazis, lawsuits, and an AI surge.\nLet me explain.\nZeiss was founded in 1846 as a microscope workshop in a German university town.\nCarl Zeiss shaped glass microscope lenses by hand for 20 years.\nIt was an artisanal process.\nUntil 1866, when he hires a young physicist, Ernst Abe,\nwho writes a math theory for how light forms an image inside a microscope.\nThis step change allows them to start making specialized lenses at scale.\nIn 1888, Zeiss dies and Abe takes over the now really valuable optics company.\nHe makes a critical decision to put the entire company in a foundation\nto protect it from looters, and he also writes this massive constitution,\nguaranteeing worker pensions, sick pay, paid vacation, and an eight-hour workday.\nAll of this before German labor laws even existed.\nIn this era, the company invents a slew of new things,\nnew types of eyeglass and camera lenses, and fun fact, even the planetarium,\nby accident.\nA Zeiss engineer built a dome onto their factory roof to project a fake sky onto.\nNext, a dark chapter.\nDuring World War II in the 1930s, Zeiss manufactured precision optics\nfor Nazi weapons systems, admittedly using forced labor to do so.\nIt's a black mark that the company doesn't try to hide.\nIn 1945, as the Americans occupy this part of Germany,\nZeiss effectively gets split into two parts,\none on either side of the iron curtain.\nBoth companies stay named Zeiss, and for the next 40 years,\nthey compete head-on, suing each other for the trademark the whole way.\nIn 1999, the company re-merged during German reunification.\nAround the same time, a small company called ASML in the Netherlands got started.\nIn our ASML video, we talked about how EUV lithography machines work.\nThey rely heavily on lasers directing EUV light\ninto silicon wafers to etch patterns.\nTo do this, they go through a series of lenses to refract that light\nand mirrors our lenses.\nZeiss made the best ones.\nThus, a deep partnership between the companies was born.\nASML has a total monopoly on EUV litho,\nand they've said themselves they would be toast without Zeiss.\nIn November 2016, ASML tried to buy into the company.\nThey paid a billion euros and only got a 24.9% stake\nin one of the many Zeiss subsidiaries.\nThe parent company is still owned by exactly one shareholder,\nthe same foundation that Abe set up back in the 1800s.\nThat semiconductor business, the part, is now worth $5 billion,\ngrowing 23% a year and is 42% of Zeiss.\nOne of the most critical companies in all of chip manufacturing,\nand it's not even for sale.\nNot to anyone.\nImpressive foresight, pun intended.",
  "Dbq1_X8Jg7Z": "This is the weirdest company winning in AI part two.\nLast time we talked about toilets and this time we're talking about the people who make\nMSG, Ajinamoto. The Japanese seasoning company that makes your food taste savory\nalso makes a tiny film layer that's almost invisible\nand yet basically every high performance chip wouldn't work without it.\nLet me explain. In order to get power into chips and data out of them\nyou need to connect them to PCBs. In the olden days you'd add metal legs\naround the edges of chips but as chips advanced you needed more and more\nto the tune of thousands so we ran out of space. Instead\nthey started using multiple layers of copper wiring stacked underneath the chip\nbetween it and the board. This is called packaging substrate.\nIn order to have the copper not hit each other you needed to insulate it with\nsomething. That insulation layer has a bunch of\nreally strict requirements. It needs to be drillable to withstand\nthousands of perfect microscopic holes. It can't move or expand too much when it\ngets heated up. It has to be invisible to electricity and\nit needs to stay flawless at big lengths. The film is thinner than one human hair\nand gets shipped in huge rolls that need to stay intact.\nFor years the industry used ink between these layers of chips\nbut it went on unevenly and trapped air bubbles.\nMeanwhile this Japanese food ingredient company Ajinamoto\nhad been selling MSG since 1909. Around 1970\nMSG had a big PR challenge as people linked it to health scares\nso the company looked around what they had for R&D expansion opportunities\nbeyond this single product. Lucky coincidence\nMSG's chemical structure is eerily similar to the plastics used inside\nelectronics. They're basically cousins so they studied\nit for 20 years with nothing to sell. Then finally in 1996\na CPU maker knocked on their door basically saying hey this ink is failing\nus could you make us something better? Ajinamoto did a four-month sprint\nand came up with this insulating film that was just perfect.\nFor the next 25 years they held a 95% monopoly\nacross the space and their insulating film is found inside virtually\nevery single personal computer and chips made by Intel,\nNvidia, AMD and more. It's a sneaky good business too because it's super hard to\ncopy. They hold hundreds of patents and they\nco-develop each film layer alongside the chip maker\nso they get insider intel on all the requirements up to five years earlier\nthan any competitor. Over the last few years the AI boom has\nmeant bigger chips, more layers and more film. Ajinamoto's chip\nmaterials profit jumped 35% last year to about 350 million now 30%\nof the entire company's profit at margins above 50%.\nThey just raised prices 30% and nobody blinked an eye.\nKind of the same story as Toilets, an old boring product built the empire\nbut now a previously invisible side quest is printing all of the money.",
  "Dba3INFi-0v": "You're so wrong if you think Stripe is just a payments company, it's a whole self-contained universe.\nThis is part eight in our charts and crafts series explaining top private tech companies.\nI never quite understood how literal Stripe's motto increasing the GDP of the internet was.\nLet me explain. Stripe was founded by two brothers who grew up in rural Ireland,\nPatrick and John Collison, to fix a pain point from their earlier company, accepting payments online.\nBefore Stripe, if you wanted to sell t-shirts online, you'd build a website,\nthen grind through a set of five or more clunky steps behind the scenes.\nYou'd set up a merchant account, which takes weeks of paperwork, install a payment gateway,\nplug into a payment processor, pass CPI compliance, and add a fraud detection system.\nTheir solution was to put all of that mess into a tidy single product,\none any developer could install with just seven lines of code.\nThis created a boom in economic activity because suddenly far more people could sell things online.\nThe scale of that boom is kind of mind-blowing. In 2024, 1.4 trillion flowed through Stripe,\nabout 1.3% of the entire planet's GDP. Last year, that hit 1.9 trillion, 1.6% of global GDP.\nSo at its core, yes, Stripe is a payments business. But on top, they've built a whole\nuniverse of products that reinforce them as a central hub for every business on the internet.\nYou can incorporate on Stripe, add revenue products like billing and tax,\nmanage your money, and then do some frontier stuff like stable clients and AI agents.\nTogether, there's a beautiful flywheel effect from a company's birth through global scale.\nBut the Collison brothers have always had higher order missions too\nthat wrap around all of these businesses. And I think that flywheel shows the true soul of Stripe.\nSupported by the primary businesses, they've built some surprising ones.\nStripe Press, a real physical book publishing house,\nPublic Goods, which includes nearly $2 billion to jumpstart carbon removal,\nand $500 million to fund research to eliminate respiratory disease.\nAnd Progress Studies, a whole intellectual movement to understand how technology\nand society can actually advance together. All of these reflect the ethos of two brothers\nwho've seen Stripe as an economic utility more than a payments company. Stripe is famously\nstill private. It raised just $2.2 billion at $159 billion valuation,\nand it's meaningfully profitable too, with an estimated $6 billion revenue just last year.\nUnsurprisingly, Stripe is a founder factory. More than 170 companies have been created by its alumni,\nincluding OpenAI by Greg Brockman, who was Stripe employee number four,\nand Anthropic by Daniela Amade, who was Stripe employee number 45.\nThere's a reason the Collison brothers are valley legends.\nThey're more like directors of this whole Stripe cinematic universe.",
  "Dci1iaRBTW_": "How do you maximize the usefulness of this super smart thing?\nYou have to make this the center of everything you do.\nSo it connects to all your software.\nIt knows who you are.\nIt knows your goals, your priorities, what you worked on yesterday,\nwhat you want to automate tomorrow,\nand it has access to all the important contacts around your business, right?\nThis could include your contacts, your pricing sheet, your product sheet,\nyour marketing strategy.\nWhat you want to do is bring everything locally as much as you can,\nsave it as folders and file,\nand then anything that needs to stay in the software can stay in the software, right?\nYour QuickBooks or Shopify give AI the keys to connect to these softwares, right?\nSo the core thing is really just organize everything,\nhaving the structure so the AI knows where everything is and can actually see it.",
  "DcEVvZgq70k": "Claude Opus 4.5 has completely transformed how I do my tax\nand bookkeeping.\nThe model is especially impressive with its ability to run long horizon agentic work.\nNaturally, I gave it access to my current bookkeeping automation and I pointed out several\nweak points and made major updates.\nIn this video, I'm going to show you my updated bookkeeping automation.\nI've also transformed my setup into a plug and play template.\nSo I'll show you how you can install it and customize to your own business, even if you're\nnot technical.",
  "Db_KPIDCtwU": "AI data center is going to make electricity cheaper, not more expensive in the long run.\nOkay, hear me out. If we plug these massive data center into an already constrained grid\nwithout adding new power, then yes, it's competing with regular households,\nit's driving the electricity bill up. However, all these major tech companies have signed a\npledge with the White House committing to either build their own power plant,\nor pay for the infrastructure upgrade their data centers need.\nIf these AI companies are so hungry for power, let them also be the power company.\nSo instead of just taking electricity from an existing grid,\ntheir demand is triggering a massive build out of power plant,\ntransmission line, and other infrastructure around it.\nAnd this is where the excess supply, surplus, and major infrastructure upgrade\nare going to lower our household electricity bill in the next three to five years.",
  "Dcdv14nqzIs": `People underestimate what rich looks like, and it's making them worse at their own careers.
The visible version often comes with a payment plan attached: the car, the apartment, the luxury bag.
Once that number is fixed, subconsciously you stop negotiating hard. You stop pushing back, and you start taking a safer project over an interesting one.
Every decision starts getting smaller, and you don't even notice it happens.
A magnetic person, the person everyone is gravitating toward without knowing the reason why, is almost never flashy with their money.
Even if they do have expensive things, they're not scared of losing it because they built the invisible part first.
They're allowed to be difficult. They're allowed to choose interesting projects because they have the status and reputation that they've already built, which gives them that flexibility and confidence to truly build a wealthy lifestyle.`,
  "DciFXHlqlwl": `Let's talk about the Etched versus Nvidia war, because Etched just raised $700 million at a $21 billion valuation on a bet that Nvidia is doing inference wrong.
Nvidia's chips are general purpose: train a model, run a model. That flexibility, though, is the reason they won the AI race, because for years no one knew what AI would actually need. So everyone bought the thing that does everything.
Etched's argument, though, is that inference, the part that happens after you hit enter, is really two stages with opposite needs.
The first is prefill, the part where the model reads your prompt. It processes every word at the same time, so the chip is doing a lot of math-intensive work. That stage is compute intensive.
The second is decode, where it generates the response one step at a time. Each step, though, has to pull the weights of the model back out of memory, so that stage is memory intensive.
Nvidia GPUs are shipped with a balance between compute power and memory bandwidth. So whichever stage you're in, one part of the chip is sitting idle.
Etched builds separate hardware for each of the stages.
Why this is an actual threat to Nvidia is because Nvidia's dominance was built on training. But training only happens once. Inference happens every time someone uses AI, and now that's the bigger and faster-growing half of the market.`,
  "Dch0_ebOUNx": `Take a look at this video. Why can you learn to flip a pancake just by watching someone else do it, but a robot somehow needs a thousand tries?
That's the question at the center of this major breakthrough for the field of robotics. Skild AI just announced a new model called S1 that lets you show a robot one video of a person doing a task, even if it's 10 minutes long and one that a robot has never seen before, and it just does it without any programming, retraining, or engineers teleoperating.
The reason you don't have a robot in your house that works well isn't because of the hardware. It's because teaching a robot is absurdly expensive and time-consuming right now.
To teach a robot one task, humans essentially have to puppeteer it through the same motions over and over again for anywhere from 50 to 100 hours. If you want a second task, you have to restart the entire process.
This is why robotics has only really ever made sense in warehouses and factories where you have the same motion repeating thousands of times a day.
Language models actually had this exact same problem. Before ChatGPT, you had to train a separate model for translation, another one for summarizing, and another for sorting emails. Each one needed its own data and training run.
What made ChatGPT feel like a breakthrough moment was that it was one model where you typed anything you wanted, maybe added an example, and it could just do it.
Researchers call this in-context learning, which is when a model can learn from whatever you put in front of it without changing its brain. The big breakthrough here is that S1 is in-context learning for robots, and it crossed three major hurdles.
The first is the embodiment gap. The videos fed to the model show humans in different rooms from very different angles, and you aren't giving the model any information about force, touch, or how robot bodies should work. So it has to figure out what the human is trying to accomplish and translate that into its own arms.
The second breakthrough is around long-horizon tasks. A lot of robot demos today are short clips because small mistakes notoriously compound and snowball. S1 can keep a whole video prompt in its memory, like a checklist, and constantly check its progress against it.
The third is generalization, the ability to do things it was never trained on. When it flipped a pancake, Skild's own team didn't believe it. They spent two days searching all one million hours of training data for pancake flipping and found nothing.
From learning from a million hours of other tasks, the robot mastered basic moves like gripping, lifting, and rotating its wrist, and applied them to new actions.
Human brains are pretty awesome because we don't need a thousand examples to learn something. But for the first time ever, teaching a robot might be as simple as recording a video on your phone.`,
  "Dckh_D0u2r3": `Nvidia is reportedly acquiring Hugging Face for $12.9 billion.
For people less familiar, Hugging Face is sort of like the GitHub for AI models. About 3 million public model repositories and a million datasets live there.
Developers go there to download and convert those models into something they can run on their own hardware. Usually the files from these labs are too big to run on your own computer, so you have to shrink and repackage them.
Companies pay monthly for private accounts on Hugging Face and pay them to rent computers to run models.
Nvidia, as we know, makes the chips that all of this stuff runs on. It's also one of the biggest publishers of free models.
But right now Nvidia has a tricky situation where its biggest customers, like OpenAI, Google, Amazon, and Anthropic, are all trying to design their own chips. If they have their own chips, they're no longer going to be Nvidia customers.
So in some ways, open models are a hedge. OpenAI actively has a chip called Jalapeño. Google already has its TPUs. But the other 100,000 companies downloading models from Hugging Face likely won't develop their own chips and will just buy whatever is for sale.
Nvidia is incentivized to sell to a bunch of these smaller customers who are locked in and can't leave, over four really big model providers that are already halfway out the door.
If Nvidia owns Hugging Face, it can try to make sure its products are always pushed first and become the hardware that all of these models run on.
So far, nothing is signed. But if it does hold, it is a $12.9 billion outcome, reportedly about 80 times Hugging Face's revenue this year.
Hugging Face was last valued at $4.5 billion in 2023, so this is nearly triple in three years. It's a pretty big outcome for a 10-year-old company that originally started in 2016 as a chatbot app.`,
  "DcsHtkAOkOX": `Let's talk about a few recent hot startup rounds.
A four-month-old company, Instinct, is raising a $250 million Series B at a $2.5 billion valuation. It's a personal AI assistant that connects to your email, calendar, and devices, including your screen, audio, and location.
It doesn't live in a separate app, so you text or WhatsApp it and it can book you a flight, get you a dinner reservation, or even Oppenheimer 70mm IMAX tickets.
The founder, Noah Shin, is 23, and he was the lead author on a popular paper on self-correcting agents with over 7,000 citations. He was also a very early employee at Sierra, Brett Taylor's customer service agent company.
Unlike some other chatbots, Instinct runs its own persistent cloud computer with a browser signed into your accounts, so it can keep working between your messages and operate on services with no API. As of right now, it's still invite only.
Etched raised $700 million at a $21 billion valuation, led by the quant firm Jane Street. This comes less than a month after a $300 million Series C at a $10.3 billion valuation, meaning it doubled its valuation in 26 days and 4x'd it in eight months since its December round.
The three founders are Harvard dropouts Gavin Uberti, Chris Zhu, and Robert Wachen, who met in Math 55, often referenced as one of the hardest undergraduate math classes in the country.
They designed chips that only do inference, which is the process of running AI models, not training them. GPUs are general purpose, so they can run pretty much anything. But for that flexibility, you pay in speed and power.
Etched strips all of that out and optimizes only for faster, cheaper tokens, which matters because inference is overtaking training as the bigger compute market.
Interestingly, Jane Street isn't just the lead investor. It's also one of Etched's first customers and tested its chips by putting a rack in its own data center. Jane Street liked the results so much that it decided to double down.
Starcloud raised $250 million at a $2.3 billion valuation to build data centers in space. Nvidia and Cisco joined this round, and the valuation has doubled since March.
The big bottleneck for AI right now isn't just chips. It's also power. Data centers are fighting over grid connections and land, but in orbit you can get near-constant sunlight.
Starcloud has already flown an Nvidia H100 into orbit last November and ran its first AI training job in space. Its larger plan is to have over 80,000 satellites and 20 gigawatts of orbital compute.`,
} as const;
