import { CREATOR_SCRIPTS } from "../../components/media-os/creator-scripts.ts";
import type { MediaSourceRecord } from "./types.ts";

/**
 * The v1 source catalog is client-safe. The repository mirrors these records
 * into media_items, while Media can render the same canonical IDs and assets.
 */
export const MEDIA_CATALOG = [
  {
    id: "DZFnttWijxS",
    title: "Databricks, explained in two minutes",
    creator: "nataliefratto",
    sourceAccount: "@nataliefratto",
    platform: "Instagram",
    postedAt: "2026-06-02T15:11:56.000Z",
    duration: "2:09",
    thumbnailUrl: "/media/instagram/nataliefratto-DZFnttWijxS-thumbnail.jpg",
    videoUrl: "/media/instagram/nataliefratto-DZFnttWijxS.mp4",
    sourceUrl: "https://www.instagram.com/nataliefratto/reel/DZFnttWijxS/",
    thumbnailText: "Top private tech companies Part 7: Databricks",
    transcript: CREATOR_SCRIPTS.DZFnttWijxS,
    caption: `Databricks is on every list of hot companies, but before making this video, I’m not sure I could have explained it to you with a gun to my head. Did the research for all of us - here’s the 2 min pretty version!

#databricks #developer #technology #ai #startup`,
    summary: "A researched, two-minute explanation of what Databricks does and why the company gets so much attention.",
    metrics: { likes: "218.6K", comments: "714", reposts: "2.9K" },
  },
  {
    id: "Dcd0nZkCnAa",
    title: "Crusoe, private tech company part 9",
    creator: "nataliefratto",
    sourceAccount: "@nataliefratto",
    platform: "Instagram",
    postedAt: "2026-08-25T14:14:43.000Z",
    duration: "2:21",
    thumbnailUrl: "/media/instagram/nataliefratto-Dcd0nZkCnAa-thumbnail.jpg",
    videoUrl: "/media/instagram/nataliefratto-Dcd0nZkCnAa.mp4",
    sourceUrl: "https://www.instagram.com/nataliefratto/reel/Dcd0nZkCnAa/",
    thumbnailText: "Top private tech companies Part 9: Crusoe",
    transcript: CREATOR_SCRIPTS.Dcd0nZkCnAa,
    caption: `Top private tech companies, part 9: Crusoe

#crusoe #energy #datacenter #technology #ai @crusoe.ai`,
    summary: "Part nine of a series on leading private tech companies, focused on energy and AI infrastructure company Crusoe.",
    metrics: { likes: "8.1K", comments: "57", reposts: "148" },
  },
  {
    id: "DcQ5PNeC6-s",
    title: "A notebook theory on SpaceX and Midjourney",
    creator: "nataliefratto",
    sourceAccount: "@nataliefratto",
    platform: "Instagram",
    postedAt: "2026-08-20T13:44:27.000Z",
    duration: "2:06",
    thumbnailUrl: "/media/instagram/nataliefratto-DcQ5PNeC6-s-thumbnail.jpg",
    videoUrl: "/media/instagram/nataliefratto-DcQ5PNeC6-s.mp4",
    sourceUrl: "https://www.instagram.com/nataliefratto/reel/DcQ5PNeC6-s/",
    thumbnailText: "Predication: AI labs are becoming American zaibatsus",
    transcript: CREATOR_SCRIPTS["DcQ5PNeC6-s"],
    caption: `Sharing more of my scribbled notebook diagrams & theories with you. Armchair tech economist here - just something I’m noodling on. What do you think?

#spacex #midjourney #tech #technology #ai`,
    summary: "A working notebook theory that brings SpaceX, Midjourney, technology, and AI into the same discussion.",
    metrics: { likes: "726", comments: "22", reposts: "10" },
  },
  {
    id: "Dcd1OqeCXsL",
    title: "Cinematic caption edits with Hyperframes",
    creator: "softgirlnocode",
    sourceAccount: "@softgirlnocode",
    platform: "Instagram",
    postedAt: "2026-08-25T14:19:14.000Z",
    duration: "0:31",
    thumbnailUrl: "/media/instagram/softgirlnocode-Dcd1OqeCXsL-thumbnail.jpg",
    videoUrl: "/media/instagram/softgirlnocode-Dcd1OqeCXsL.mp4",
    sourceUrl: "https://www.instagram.com/softgirlnocode/reel/Dcd1OqeCXsL/",
    thumbnailText: "I turned this editing style into an AI skill",
    transcript: CREATOR_SCRIPTS.Dcd1OqeCXsL,
    caption: `I have an updated YouTube tutorial dropping on the hyperframes step-by-step set up, stay tuned!

Comment “skill” for this cinematic caption edits.
#realestatevideo #tech #aitutorial #aitools #aimarketing`,
    summary: "A short preview of cinematic caption edits, with an upcoming Hyperframes setup tutorial.",
    metrics: { likes: "1.8K", comments: "3.8K", reposts: "42" },
  },
  {
    id: "DcYhrFHiVw8",
    title: "Editing videos and AI animations live",
    creator: "softgirlnocode",
    sourceAccount: "@softgirlnocode",
    platform: "Instagram",
    postedAt: "2026-08-23T12:53:37.000Z",
    duration: "1:34",
    thumbnailUrl: "/media/instagram/softgirlnocode-DcYhrFHiVw8-thumbnail.jpg",
    videoUrl: "/media/instagram/softgirlnocode-DcYhrFHiVw8.mp4",
    sourceUrl: "https://www.instagram.com/softgirlnocode/reel/DcYhrFHiVw8/",
    thumbnailText: "",
    transcript: CREATOR_SCRIPTS.DcYhrFHiVw8,
    caption: `Let’s do a live editing session together so I can show you how I usually edit my videos and add animations using AI.

Quick preface: I didn’t include the Hyperframe project setup in this video. I have a full YouTube video that walks you through the entire setup step by step. Comment “LINK” and I’ll send it to you.

There are also two iterations I left out of this video, but they’re essentially just me reviewing the final edit and speaking to the AI to make changes to anything I don’t like.
#tech #aiforcreators #editor #video #aiforbusiness`,
    summary: "A live editing session showing a typical video workflow and how AI is used to add animations and revise the final edit.",
    metrics: { likes: "821", comments: "652", reposts: "20" },
  },
  {
    id: "DcWQxOriYU8",
    title: "Giving AI the context it needs",
    creator: "softgirlnocode",
    sourceAccount: "@softgirlnocode",
    platform: "Instagram",
    postedAt: "2026-08-22T15:44:50.000Z",
    duration: "0:57",
    thumbnailUrl: "/media/instagram/softgirlnocode-DcWQxOriYU8-thumbnail.jpg",
    videoUrl: "/media/instagram/softgirlnocode-DcWQxOriYU8.mp4",
    sourceUrl: "https://www.instagram.com/softgirlnocode/reel/DcWQxOriYU8/",
    thumbnailText: "Steal my 9 AI setup questions",
    transcript: CREATOR_SCRIPTS.DcWQxOriYU8,
    caption: `kind of loving how the edit matches my shirt and nails lol

Your AI is only as useful as the context you give it. This intake gets the important stuff out of your head so your AI can actually understand how you work without you having to explain yourself over and over again.

#techtok #aiautomation #aiforbusiness #aiforentrepreneurs #womeninstem`,
    summary: "A context intake designed to help AI understand how someone works without repeated explanations.",
    metrics: { likes: "128", comments: "101", reposts: "3" },
  },
  {
    id: "DcLtNI2i8yU",
    title: "Why Zeiss Is the Weirdest Company Winning in AI",
    creator: "nataliefratto",
    sourceAccount: "@nataliefratto",
    platform: "Instagram",
    postedAt: "2026-08-18T13:22:24.000Z",
    duration: "2:42",
    thumbnailUrl: "/media/instagram/nataliefratto-DcLtNI2i8yU-thumbnail.jpg",
    videoUrl: "/media/instagram/nataliefratto-DcLtNI2i8yU.mp4",
    sourceUrl: "https://www.instagram.com/p/DcLtNI2i8yU/",
    thumbnailText: "The weirdest company winning in AI, part 3: Zeiss",
    transcript: CREATOR_SCRIPTS["DcLtNI2i8yU"],
    caption: "The weirdest company winning in AI, part 3: Zeiss\n\n#ai #technology #asml #explainervideo @zeissgroup @zeiss_planetariums",
    summary: "How a 19th-century optics workshop became an indispensable supplier to ASML and modern AI chip manufacturing.",
    metrics: { likes: "6.9K", comments: "61", reposts: "—" },
  },
  {
    id: "Dbq1_X8Jg7Z",
    title: "How an MSG Maker Became Essential to AI Chips",
    creator: "nataliefratto",
    sourceAccount: "@nataliefratto",
    platform: "Instagram",
    postedAt: "2026-08-05T19:07:24.000Z",
    duration: "2:55",
    thumbnailUrl: "/media/instagram/nataliefratto-Dbq1_X8Jg7Z-thumbnail.jpg",
    videoUrl: "/media/instagram/nataliefratto-Dbq1_X8Jg7Z.mp4",
    sourceUrl: "https://www.instagram.com/p/Dbq1_X8Jg7Z/",
    thumbnailText: "The weirdest company winning in AI, part 2: Ajinomoto (MSG-maker)",
    transcript: CREATOR_SCRIPTS["Dbq1_X8Jg7Z"],
    caption: "Not that kind of chips.\n\nFirst Charts & Crafts video with a prop 😏 this one was so fun to learn about.\n\n#ai #semiconductors #technology #tech #explainer",
    summary: "How Ajinomoto turned food-chemistry expertise into the insulating film used in nearly every high-performance chip.",
    metrics: { likes: "185.9K", comments: "1.1K", reposts: "—" },
  },
  {
    id: "Dba3INFi-0v",
    title: "Why Stripe Is More Than a Payments Company",
    creator: "nataliefratto",
    sourceAccount: "@nataliefratto",
    platform: "Instagram",
    postedAt: "2026-07-30T14:06:23.000Z",
    duration: "2:48",
    thumbnailUrl: "/media/instagram/nataliefratto-Dba3INFi-0v-thumbnail.jpg",
    videoUrl: "/media/instagram/nataliefratto-Dba3INFi-0v.mp4",
    sourceUrl: "https://www.instagram.com/p/Dba3INFi-0v/",
    thumbnailText: "Top private tech companies Part 8: Stripe",
    transcript: CREATOR_SCRIPTS["Dba3INFi-0v"],
    caption: "Part 8: Stripe is one of the most fabled companies in Silicon Valley, and it’s so much more than a payments company…\n\n#stripe #fintech #startup #venturecapital #technology",
    summary: "How Stripe expanded from seven-line payments integration into an economic platform, founder factory, and mission-driven institution.",
    metrics: { likes: "11.7K", comments: "93", reposts: "—" },
  },
  {
    id: "Dci1iaRBTW_",
    title: "Why Every Business Needs an AI Operating System",
    creator: "softgirlnocode",
    sourceAccount: "@softgirlnocode",
    platform: "Instagram",
    postedAt: "2026-08-27T12:36:40.000Z",
    duration: "0:44",
    thumbnailUrl: "/media/instagram/softgirlnocode-Dci1iaRBTW_-thumbnail.jpg",
    videoUrl: "/media/instagram/softgirlnocode-Dci1iaRBTW_.mp4",
    sourceUrl: "https://www.instagram.com/p/Dci1iaRBTW_/",
    thumbnailText: "explaining to my biz owner friend why he needs AI operating system (pt.1)",
    transcript: CREATOR_SCRIPTS["Dci1iaRBTW_"],
    caption: "What’s the opposite of mansplaining 😂😂\n\n#aiautomation #smallbusinessowners #enterpreneurs #ecommerce #freelancer",
    summary: "A practical argument for making AI the center of a business by connecting its goals, files, contacts, and core software.",
    metrics: { likes: "43", comments: "4", reposts: "—" },
  },
  {
    id: "DcEVvZgq70k",
    title: "POV: Your Editor Suddenly Ghosts You",
    creator: "softgirlnocode",
    sourceAccount: "@softgirlnocode",
    platform: "Instagram",
    postedAt: "2026-08-15T16:43:18.000Z",
    duration: "0:47",
    thumbnailUrl: "/media/instagram/softgirlnocode-DcEVvZgq70k-thumbnail.jpg",
    videoUrl: "/media/instagram/softgirlnocode-DcEVvZgq70k.mp4",
    sourceUrl: "https://www.instagram.com/p/DcEVvZgq70k/",
    thumbnailText: "POV: nothing spikes your cortisol like your editor suddenly ghosting",
    transcript: CREATOR_SCRIPTS["DcEVvZgq70k"],
    caption: "Based on real story \n\n#tech #editor #chatgpt #claude #relatable",
    summary: "A creator-relatable setup about an editor disappearing, followed by a walkthrough of an AI-updated bookkeeping automation and template.",
    metrics: { likes: "3.6K", comments: "103", reposts: "—" },
  },
  {
    id: "Db_KPIDCtwU",
    title: "How AI Data Centers Could Make Electricity Cheaper",
    creator: "softgirlnocode",
    sourceAccount: "@softgirlnocode",
    platform: "Instagram",
    postedAt: "2026-08-13T16:31:06.000Z",
    duration: "0:48",
    thumbnailUrl: "/media/instagram/softgirlnocode-Db_KPIDCtwU-thumbnail.jpg",
    videoUrl: "/media/instagram/softgirlnocode-Db_KPIDCtwU.mp4",
    sourceUrl: "https://www.instagram.com/p/Db_KPIDCtwU/",
    thumbnailText: "AI could make electricity cheaper",
    transcript: CREATOR_SCRIPTS["Db_KPIDCtwU"],
    caption: "In the short term, where the grid is already tight, the evidence currently points more toward data centers raising costs. In the longer term, they can lower the cost per kWh if they pay for the infrastructure they cause and make better use of infrastructure that would otherwise sit underutilized.\n\nIn March 2026, Amazon, Google, Meta, Microsoft, OpenAI, Oracle and xAI signed the White House Ratepayer Protection Pledge. They committed to build, bring or buy the new generation their data centers require, pay for the grid upgrades, and negotiate structures where they keep paying for infrastructure even if they don’t end up using all the power.\n\n#technews #datacenter #electricity #google #amazon",
    summary: "Why power-hungry AI data centers could eventually lower household electricity costs by funding new generation and grid infrastructure.",
    metrics: { likes: "173", comments: "42", reposts: "—" },
  },
  {
    id: "Dcdv14nqzIs",
    title: "Invisible Money Is What Rich Actually Looks Like",
    creator: "maitrimangal",
    sourceAccount: "@maitrimangal",
    platform: "Instagram",
    postedAt: "2026-08-25T13:30:55.000Z",
    duration: "0:49",
    thumbnailUrl: "/media/instagram/maitrimangal-Dcdv14nqzIs-thumbnail.jpg",
    videoUrl: "/media/instagram/maitrimangal-Dcdv14nqzIs.mp4",
    sourceUrl: "https://www.instagram.com/p/Dcdv14nqzIs/",
    thumbnailText: "Become Magnetically Wealthy: Understand the concept of Invisible Money",
    transcript: CREATOR_SCRIPTS.Dcdv14nqzIs,
    caption: "Invisible Money Concepts",
    summary: "Why status, reputation, and career freedom are a more durable form of wealth than visible purchases.",
    metrics: { likes: "422", comments: "8", reposts: "—" },
  },
  {
    id: "DciFXHlqlwl",
    title: "Etched vs Nvidia: The Inference Chip War",
    creator: "maitrimangal",
    sourceAccount: "@maitrimangal",
    platform: "Instagram",
    postedAt: "2026-08-27T05:55:49.000Z",
    duration: "1:18",
    thumbnailUrl: "/media/instagram/maitrimangal-DciFXHlqlwl-thumbnail.jpg",
    videoUrl: "/media/instagram/maitrimangal-DciFXHlqlwl.mp4",
    sourceUrl: "https://www.instagram.com/p/DciFXHlqlwl/",
    thumbnailText: "Let's talk Etched vs Nvidia",
    transcript: CREATOR_SCRIPTS.DciFXHlqlwl,
    caption: "Etched vs Nvidia!!",
    summary: "Why Etched is betting specialized inference chips can beat Nvidia's general-purpose GPUs on speed and power.",
    metrics: { likes: "631", comments: "11", reposts: "—" },
  },
  {
    id: "Dch0_ebOUNx",
    title: "The ChatGPT Moment for Robotics",
    creator: "zauey.talks",
    sourceAccount: "@zauey.talks",
    platform: "Instagram",
    postedAt: "2026-08-27T03:32:50.000Z",
    duration: "2:50",
    thumbnailUrl: "/media/instagram/zaueytalks-Dch0_ebOUNx-thumbnail.jpg",
    videoUrl: "/media/instagram/zaueytalks-Dch0_ebOUNx.mp4",
    sourceUrl: "https://www.instagram.com/p/Dch0_ebOUNx/",
    thumbnailText: "ChatGPT moment for robotics: SKILD S1",
    transcript: CREATOR_SCRIPTS.Dch0_ebOUNx,
    caption: `The ChatGPT Moment for Robotics 🧠

🤖 @skildai released S1. You show a robot one video of a person doing a task (even a 10-minute task it’s never seen) and it does it.
⏱️ Teaching a robot one task currently takes 50–100 hours of humans puppeteering it through the motions, plus a full retrain.
🧠 S1 is in-context learning for robots. Same idea as ChatGPT replacing a separate model for every job, except the prompt is a video instead of text.
🥞 S1 flipped a pancake despite no pancake-flipping anywhere in its million hours of training data. It combined gripping, lifting, and wrist rotation on its own.

#robotics #ai #mechanicalengineering #tech #startup

Disclosure: This is not investment advice and views expressed are my own.`,
    summary: "How Skild AI's S1 learns unfamiliar robot tasks from a single demonstration video without retraining.",
    metrics: { likes: "3K", comments: "48", reposts: "—" },
  },
  {
    id: "Dckh_D0u2r3",
    title: "Why Nvidia Wants Hugging Face",
    creator: "zauey.talks",
    sourceAccount: "@zauey.talks",
    platform: "Instagram",
    postedAt: "2026-08-28T04:44:43.000Z",
    duration: "1:44",
    thumbnailUrl: "/media/instagram/zaueytalks-Dckh_D0u2r3-thumbnail.jpg",
    videoUrl: "/media/instagram/zaueytalks-Dckh_D0u2r3.mp4",
    sourceUrl: "https://www.instagram.com/p/Dckh_D0u2r3/",
    thumbnailText: "Nvidia x Hugging Face",
    transcript: CREATOR_SCRIPTS.Dckh_D0u2r3,
    caption: `Nvidia x Hugging Face $12.9B Deal Explained

#tech #nvidia #huggingface #ai #startup

Disclosure: Views expressed are my own. This is not investment advice. This is for informational and educational purposes only.`,
    summary: "Why owning the distribution hub for open AI models could protect Nvidia as its largest customers build their own chips.",
    metrics: { likes: "2.1K", comments: "35", reposts: "—" },
  },
  {
    id: "DcsHtkAOkOX",
    title: "Hot Startup Rounds: Instinct, Etched, and Starcloud",
    creator: "zauey.talks",
    sourceAccount: "@zauey.talks",
    platform: "Instagram",
    postedAt: "2026-08-31T03:28:41.000Z",
    duration: "2:22",
    thumbnailUrl: "/media/instagram/zaueytalks-DcsHtkAOkOX-thumbnail.jpg",
    videoUrl: "/media/instagram/zaueytalks-DcsHtkAOkOX.mp4",
    sourceUrl: "https://www.instagram.com/p/DcsHtkAOkOX/",
    thumbnailText: "Hot startup rounds, Aug 30, 2026",
    transcript: CREATOR_SCRIPTS.DcsHtkAOkOX,
    caption: `A few recent hot startup rounds (aug 30)

🤖 Instinct is raising a $250M Series B at a $2.5B valuation to build a personal AI agent you text or call
⚡ Etched raised $700M at a $21B valuation to build chips that only do inference, trading GPU flexibility for cheaper, faster tokens
🛰️ Starcloud raised $250M at a $2.3B valuation to build solar-powered data centers in orbit, betting the AI bottleneck is power and not chips

#tech #startups #venturecapital #founder #siliconvalley

Disclosure: Views expressed are my own. This is not investment advice. This is for informational and educational purposes only.`,
    summary: "A breakdown of fresh funding rounds for Instinct, Etched, and Starcloud across AI agents, inference chips, and orbital data centers.",
    metrics: { likes: "808", comments: "12", reposts: "—" },
  },
] as const satisfies readonly MediaSourceRecord[];
