import Link from "next/link";
import { ITEM_STAGES, listItems } from "@/lib/db";
import { createIdea, investInResearch } from "./actions";

export const dynamic = "force-dynamic";
const labels:Record<string,string>={inbox:"Inbox",idea:"Inbox",exploring:"Exploring",developing:"Exploring",drafting:"Drafting",scripting:"Drafting",ready_to_record:"Ready to record",production:"Ready to record",editing:"Editing",ready_to_publish:"Ready to publish",published:"Published"};
const aliases:Record<string,string[]>={inbox:["inbox","idea"],exploring:["exploring","developing"],drafting:["drafting","scripting"],ready_to_record:["ready_to_record","production"],editing:["editing"],ready_to_publish:["ready_to_publish"],published:["published"]};
const researchLabels:Record<string,string>={not_researched:"Not researched",queued:"Research queued",researching:"Researching",research_ready:"Research ready",needs_input:"Needs input",approved:"Research approved"};

export default async function IdeasPage({searchParams}:{searchParams:Promise<{stage?:string}>}){
  const{stage}=await searchParams;const items=listItems();const selected=stage&&ITEM_STAGES.includes(stage as never)?stage:"all";
  const visible=selected==="all"?items:items.filter(item=>aliases[selected]?.includes(item.stage));
  const attention=items.filter(item=>["research_ready","needs_input"].includes(item.research_status)).slice(0,4);
  return <main className="mx-auto max-w-6xl px-6 py-10 text-[#262522]">
    <div className="mb-8 flex items-end justify-between gap-6"><div><p className="mb-2 text-xs font-medium uppercase tracking-[.18em] text-[#92908a]">Content pipeline</p><h1 className="text-3xl font-semibold tracking-tight">Ideas</h1><p className="mt-2 text-sm text-[#6f6d67]">Choose what deserves research, then shape researched signals into original angles.</p></div><details className="group relative"><summary className="cursor-pointer list-none rounded-md bg-[#262522] px-4 py-2 text-sm text-white">New idea</summary><form action={createIdea} className="absolute right-0 z-20 mt-2 w-80 space-y-3 rounded-xl border border-[#e6e3dc] bg-white p-4 shadow-xl"><input name="title" required autoFocus placeholder="Idea title" className="w-full rounded-md border border-[#ddd9d0] px-3 py-2 text-sm"/><textarea name="notes" placeholder="Quick thought or context" rows={3} className="w-full rounded-md border border-[#ddd9d0] px-3 py-2 text-sm"/><button className="w-full rounded-md bg-[#262522] px-3 py-2 text-sm text-white">Create idea</button></form></details></div>
    {attention.length?<section className="mb-8 rounded-2xl bg-[#171715] p-5 text-white"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-medium uppercase tracking-[.16em] text-[#aaa59b]">Needs your attention</p><h2 className="mt-1 text-xl font-semibold">Research ready for a human take</h2></div><Link href="/angle-feed" className="text-sm text-[#c8b6ff]">Open Angle Feed →</Link></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{attention.map(item=><Link key={item.id} href={`/ideas/${item.id}`} className="rounded-xl bg-[#242320] p-4 hover:bg-[#2d2b28]"><span className="text-xs text-[#c8b6ff]">{researchLabels[item.research_status]}</span><h3 className="mt-2 line-clamp-2 text-sm font-medium">{item.title}</h3><p className="mt-2 line-clamp-2 text-xs leading-5 text-[#b7b2a9]">{item.research_summary??"Review the dossier and add your perspective."}</p></Link>)}</div></section>:null}
    <nav aria-label="Filter ideas by stage" className="mb-6 flex flex-wrap gap-2"><Link href="/ideas" aria-current={selected==="all"?"page":undefined} className={`rounded-full border px-3 py-1.5 text-xs ${selected==="all"?"border-[#262522] bg-[#262522] text-white":"border-[#e4e1da] bg-[#faf9f7] text-[#66635d]"}`}>All · {items.length}</Link>{ITEM_STAGES.map(itemStage=><Link key={itemStage} href={`/ideas?stage=${itemStage}`} aria-current={selected===itemStage?"page":undefined} className={`rounded-full border px-3 py-1.5 text-xs ${selected===itemStage?"border-[#262522] bg-[#262522] text-white":"border-[#e4e1da] bg-[#faf9f7] text-[#66635d]"}`}>{labels[itemStage]} · {items.filter(item=>aliases[itemStage].includes(item.stage)).length}</Link>)}</nav>
    {visible.length===0?<div className="rounded-xl border border-dashed border-[#d8d4cb] py-20 text-center text-sm text-[#77736c]">No ideas in this stage.</div>:<div className="overflow-hidden rounded-xl border border-[#e4e1da] bg-white">{visible.map((item,index)=><div key={item.id} className={`grid gap-4 px-5 py-4 sm:grid-cols-[1fr_auto] ${index?"border-t border-[#efede8]":""}`}><Link href={`/ideas/${item.id}`} className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="truncate text-sm font-medium">{item.title}</h2><span className="rounded-full bg-[#f2f0eb] px-2 py-0.5 text-[11px] text-[#6f6b64]">{researchLabels[item.research_status]??item.research_status}</span></div><p className="mt-1 truncate text-xs text-[#85827b]">{[item.person,item.lane,item.target_platform].filter(Boolean).join(" · ")||item.angle||"No angle yet"}</p>{item.research_summary?<p className="mt-2 line-clamp-1 text-xs text-[#6c6962]">{item.research_summary}</p>:null}</Link><div className="flex items-center gap-3 text-xs text-[#77746e]"><span>{item.source_count} source{item.source_count===1?"":"s"}</span><span className="rounded-full bg-[#f0eee9] px-2.5 py-1">{labels[item.stage]??item.stage}</span>{["inbox","idea"].includes(item.stage)?<form action={investInResearch}><input type="hidden" name="id" value={item.id}/><button className="rounded-md bg-[#262522] px-3 py-2 text-xs font-medium text-white">Explore</button></form>:null}</div></div>)}</div>}
  </main>
}
