import type { ContentSkill, ResearchProtocol, SkillId } from "./types.ts";
const research: ResearchProtocol = { sampleSize: 50, inspect: ["copy", "media", "context", "performance"], compareToAccountBaseline: true, dimensions: ["hook", "idea", "tone", "pacing", "structure", "format", "length", "CTA", "audience", "platform conventions", "over/underperformance"], separateUniversalAndPlatformPatterns: true };
const core = [
  "Preserve the selected Thomas, Brett, Seb, or Fonzi voice; never blend voices silently.",
  "Ground every factual claim and opinion in supplied sources, Delphis, or first-person input.",
  "Never invent a take, proof point, metric, quote, customer name, or experience.",
  "Treat positioning-document numbers as candidate proof points: require an approved source, as-of date, scope or denominator, and publication permission before use.",
  "Choose one primary audience and job-to-be-done before drafting; flag accidental talent-and-company message blending.",
  "Prefer product-driven routing, career intelligence, market pricing, fit, and access language; do not default to marketplace, job-board, or recruiter-agency framing.",
  "Apply Fonzi's operative voice hierarchy: truth first, then voice, then platform. Slang and lowercase are voice/platform options, not global defaults.",
  "Extract constraints and patterns, never copy source wording or beat-by-beat structure.",
] as const;
function skill(input: Omit<ContentSkill, "version" | "research" | "rules"> & { rules: readonly string[] }): ContentSkill { return { ...input, version: "1.0.0", research, rules: [...core, ...input.rules] }; }
export const CONTENT_SKILLS: readonly ContentSkill[] = [
  skill({ id: "channel-learning", title: "Channel pattern learning", purpose: "Learn how a specific account and platform earn attention and distribute ideas before writing for that channel.", platform: "universal", rules: ["Study the latest 50 posts from the selected account; analyze every attached image, thumbnail, video, spoken opening, on-screen hook, caption, and CTA rather than captions alone.", "Record real performance and compare each post with that account's own median or baseline; do not equate a bookmark or large account with virality.", "Separate the idea from its packaging: identify topic, promise, hook mechanism, thumbnail/opening-frame mechanism, caption structure, delivery, pacing, format, CTA, and platform-native distribution behavior.", "Compare winners, typical posts, and underperformers. Name repeated patterns and meaningful exceptions; do not infer a rule from one viral post.", "Create one universal pattern library and a separate playbook for X, LinkedIn, Instagram, TikTok, and YouTube. Preserve source links and observed evidence for every learned rule.", "Turn findings into testable constraints, not copied phrases. Mark confidence, sample date, evidence gaps, and when the playbook should be refreshed."], output: ["50-post sample manifest", "account baseline", "winner/typical/underperformer comparison", "hook patterns", "thumbnail/opening-frame patterns", "caption patterns", "format and pacing patterns", "platform distribution playbook", "anti-patterns", "evidence links and confidence", "next tests"] }),
  skill({ id: "idea-evaluation", title: "Idea evaluation", purpose: "Decide whether a signal can become an original, useful Fonzi idea.", platform: "universal", rules: ["Name why the source worked, the reusable pattern, grounded Fonzi angle, and copying risk.", "Classify the primary audience, audience job, content pillar, objection resolved, positioning frame, proof requirements, claim risk, and CTA route."], output: ["verdict", "evidence", "pattern", "Fonzi angle", "audience and job", "pillar and objection", "proof requirements", "CTA route", "risks"] }),
  skill({ id: "interview", title: "Founder interview", purpose: "Elicit real opinions, experience, proof, and specificity before drafting.", platform: "universal", rules: ["Ask one focused question at a time.", "Probe surprise, disagreement, lived proof, misconceptions, concrete examples, and changed behavior."], output: ["questions", "verbatim answers", "grounded claims", "open evidence gaps"] }),
  skill({ id: "short-form-script", title: "Short-form script", purpose: "Turn a grounded idea into a concise spoken video script.", platform: "short-video", rules: ["Lead with the strongest accurate idea.", "Generate at least three candidates, then critique and rank them.", "Optimize for spoken rhythm, retention, and producibility."], output: ["ranked candidates", "winning script", "ranking rationale", "source map"] }),
  skill({ id: "x-post", title: "X post", purpose: "Write concise, platform-native X posts in a selected voice.", platform: "x", rules: ["Put the surprising or technically meaningful idea first.", "Generate at least three candidates, then critique and rank them.", "Avoid generic hype, engagement bait, and unsupported certainty."], output: ["ranked candidates", "winner", "ranking rationale", "source map"] }),
  skill({ id: "linkedin-post", title: "LinkedIn post", purpose: "Write credible, useful LinkedIn posts without corporate filler.", platform: "linkedin", rules: ["Use a clear insight and concrete proof, not manufactured vulnerability.", "Generate at least three candidates, then critique and rank them."], output: ["ranked candidates", "winner", "ranking rationale", "source map"] }),
  skill({ id: "shot-list", title: "Shot list", purpose: "Translate an approved script into a practical visual plan.", platform: "short-video", rules: ["Map every shot to a script beat.", "Prefer available assets and flag missing proof or media."], output: ["timed beats", "A-roll", "B-roll", "on-screen text", "asset gaps"] }),
  skill({ id: "repurposing", title: "Repurposing", purpose: "Re-express an approved idea natively for another platform.", platform: "universal", rules: ["Preserve the core claim and source lineage.", "Rebuild structure for the destination platform instead of trimming the original."], output: ["platform variants", "adaptation notes", "source map"] }),
  skill({ id: "ai-writing-detection", title: "AI-writing detection", purpose: "Flag generic, synthetic, or unsupported writing before approval.", platform: "universal", rules: ["Flag repeated rhetorical templates, vague authority, filler transitions, false quotations, excessive symmetry, and generic hype.", "Return evidence and suggested edits; never claim authorship detection certainty."], output: ["flags", "evidence spans", "severity", "revision suggestions"] }),
] as const;
export function getContentSkill(id: SkillId): ContentSkill { const found = CONTENT_SKILLS.find((entry) => entry.id === id); if (!found) throw new Error(`Unknown content skill: ${id}`); return found; }
